"""add system jobs

Revision ID: 09790e7e4458
Revises: db148c6436b1
Create Date: 2026-07-23 01:07:13.416149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09790e7e4458'
down_revision: Union[str, Sequence[str], None] = 'db148c6436b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('result_json', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_jobs_id'), 'system_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_system_jobs_job_type'), 'system_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_system_jobs_status'), 'system_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_jobs_status'), table_name='system_jobs')
    op.drop_index(op.f('ix_system_jobs_job_type'), table_name='system_jobs')
    op.drop_index(op.f('ix_system_jobs_id'), table_name='system_jobs')
    op.drop_table('system_jobs')
    # ### end Alembic commands ###
