"""add sportmonks id to teams

Revision ID: 0b699e80eb0b
Revises: e6b3e48763ce
Create Date: 2026-07-14 03:08:01.483607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b699e80eb0b'
down_revision: Union[str, Sequence[str], None] = 'e6b3e48763ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('sportmonks_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teams_sportmonks_id'), 'teams', ['sportmonks_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_sportmonks_id'), table_name='teams')
    op.drop_column('teams', 'sportmonks_id')
    # ### end Alembic commands ###
