"""add favorite matches

Revision ID: 299828945d1c
Revises: a14f5c9e7d32
Create Date: 2026-08-17 21:23:51.664346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299828945d1c'
down_revision: Union[str, Sequence[str], None] = 'a14f5c9e7d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id', name='uq_favorite_matches_user_match')
    )
    op.create_index(op.f('ix_favorite_matches_created_at'), 'favorite_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_favorite_matches_id'), 'favorite_matches', ['id'], unique=False)
    op.create_index(op.f('ix_favorite_matches_match_id'), 'favorite_matches', ['match_id'], unique=False)
    op.create_index(op.f('ix_favorite_matches_user_id'), 'favorite_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_matches_user_id'), table_name='favorite_matches')
    op.drop_index(op.f('ix_favorite_matches_match_id'), table_name='favorite_matches')
    op.drop_index(op.f('ix_favorite_matches_id'), table_name='favorite_matches')
    op.drop_index(op.f('ix_favorite_matches_created_at'), table_name='favorite_matches')
    op.drop_table('favorite_matches')
    # ### end Alembic commands ###

