"""add sportmonks id to matches

Revision ID: 3407cd56ad47
Revises: 0b699e80eb0b
Create Date: 2026-07-14 06:21:17.570383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3407cd56ad47'
down_revision: Union[str, Sequence[str], None] = '0b699e80eb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('sportmonks_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matches_sportmonks_id'), 'matches', ['sportmonks_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_sportmonks_id'), table_name='matches')
    op.drop_column('matches', 'sportmonks_id')
    # ### end Alembic commands ###
