"""add provider webhook events

Revision ID: 4b07c8c09988
Revises: cd3cdc7326eb
Create Date: 2026-08-09 20:23:02.245557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b07c8c09988'
down_revision: Union[str, Sequence[str], None] = 'cd3cdc7326eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_provider_webhook_events_provider_event_id')
    )
    op.create_index(op.f('ix_provider_webhook_events_event_id'), 'provider_webhook_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_provider_webhook_events_event_type'), 'provider_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_provider_webhook_events_id'), 'provider_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_provider_webhook_events_processed_at'), 'provider_webhook_events', ['processed_at'], unique=False)
    op.create_index(op.f('ix_provider_webhook_events_provider'), 'provider_webhook_events', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_webhook_events_status'), 'provider_webhook_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_webhook_events_status'), table_name='provider_webhook_events')
    op.drop_index(op.f('ix_provider_webhook_events_provider'), table_name='provider_webhook_events')
    op.drop_index(op.f('ix_provider_webhook_events_processed_at'), table_name='provider_webhook_events')
    op.drop_index(op.f('ix_provider_webhook_events_id'), table_name='provider_webhook_events')
    op.drop_index(op.f('ix_provider_webhook_events_event_type'), table_name='provider_webhook_events')
    op.drop_index(op.f('ix_provider_webhook_events_event_id'), table_name='provider_webhook_events')
    op.drop_table('provider_webhook_events')
    # ### end Alembic commands ###
