"""add fouls statistics columns

Revision ID: 522e0ae6a39a
Revises: 4d8f1be294f8
Create Date: 2026-08-04 14:44:37.897741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522e0ae6a39a'
down_revision: Union[str, Sequence[str], None] = '4d8f1be294f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_statistics', sa.Column('fouls', sa.Float(), nullable=True))
    op.add_column('teams', sa.Column('fouls', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'fouls')
    op.drop_column('match_statistics', 'fouls')
    # ### end Alembic commands ###
