"""add_malx_rewards_system

Revision ID: 55680ae18f10
Revises: 5786619320af
Create Date: 2026-09-04 16:19:18.222338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55680ae18f10'
down_revision: Union[str, Sequence[str], None] = '5786619320af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_user_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id', name='uq_referrals_referred_user_id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=True)
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('reward_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_reward_transactions_event_key')
    )
    op.create_index(op.f('ix_reward_transactions_created_at'), 'reward_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_reward_transactions_event_key'), 'reward_transactions', ['event_key'], unique=False)
    op.create_index(op.f('ix_reward_transactions_id'), 'reward_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_reward_transactions_reference_id'), 'reward_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_reward_transactions_reference_type'), 'reward_transactions', ['reference_type'], unique=False)
    op.create_index(op.f('ix_reward_transactions_status'), 'reward_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_reward_transactions_transaction_type'), 'reward_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_reward_transactions_user_id'), 'reward_transactions', ['user_id'], unique=False)
    op.create_table('reward_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_points', sa.Integer(), nullable=False),
    sa.Column('pending_points', sa.Integer(), nullable=False),
    sa.Column('lifetime_earned_points', sa.Integer(), nullable=False),
    sa.Column('lifetime_redeemed_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_wallets_id'), 'reward_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_reward_wallets_user_id'), 'reward_wallets', ['user_id'], unique=True)
    op.create_table('reward_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_code', sa.String(length=100), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_redemptions_created_at'), 'reward_redemptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_id'), 'reward_redemptions', ['id'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_reward_code'), 'reward_redemptions', ['reward_code'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_reward_type'), 'reward_redemptions', ['reward_type'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_status'), 'reward_redemptions', ['status'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_subscription_id'), 'reward_redemptions', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_user_id'), 'reward_redemptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_redemptions_user_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_subscription_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_status'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_reward_type'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_reward_code'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_created_at'), table_name='reward_redemptions')
    op.drop_table('reward_redemptions')
    op.drop_index(op.f('ix_reward_wallets_user_id'), table_name='reward_wallets')
    op.drop_index(op.f('ix_reward_wallets_id'), table_name='reward_wallets')
    op.drop_table('reward_wallets')
    op.drop_index(op.f('ix_reward_transactions_user_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_transaction_type'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_status'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_reference_type'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_reference_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_event_key'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_created_at'), table_name='reward_transactions')
    op.drop_table('reward_transactions')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
