"""add logo url to teams

Revision ID: 6e8a4fa947c4
Revises: aa7caa10ff60
Create Date: 2026-07-16 21:54:52.154729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8a4fa947c4'
down_revision: Union[str, Sequence[str], None] = 'aa7caa10ff60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'logo_url')
    # ### end Alembic commands ###
