"""add fixture availability and weather tables

Revision ID: 7dd0a1fefeca
Revises: b7e2d4a9c631
Create Date: 2026-08-04 05:27:58.250438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd0a1fefeca'
down_revision: Union[str, Sequence[str], None] = 'b7e2d4a9c631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sportmonks_absence_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=200), nullable=False),
    sa.Column('player_image', sa.String(length=500), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('absence_type_id', sa.Integer(), nullable=True),
    sa.Column('absence_name', sa.String(length=200), nullable=True),
    sa.Column('absence_code', sa.String(length=150), nullable=True),
    sa.Column('absence_category', sa.String(length=50), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_absences_absence_type_id'), 'fixture_absences', ['absence_type_id'], unique=False)
    op.create_index(op.f('ix_fixture_absences_fixture_id'), 'fixture_absences', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_fixture_absences_id'), 'fixture_absences', ['id'], unique=False)
    op.create_index(op.f('ix_fixture_absences_player_id'), 'fixture_absences', ['player_id'], unique=False)
    op.create_index(op.f('ix_fixture_absences_sportmonks_absence_id'), 'fixture_absences', ['sportmonks_absence_id'], unique=True)
    op.create_index(op.f('ix_fixture_absences_team_id'), 'fixture_absences', ['team_id'], unique=False)
    op.create_table('fixture_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sportmonks_lineup_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=200), nullable=False),
    sa.Column('player_image', sa.String(length=500), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('position_name', sa.String(length=100), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('lineup_type_id', sa.Integer(), nullable=False),
    sa.Column('formation_field', sa.String(length=20), nullable=True),
    sa.Column('formation_position', sa.Integer(), nullable=True),
    sa.Column('formation', sa.String(length=30), nullable=True),
    sa.Column('is_predicted', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_lineups_fixture_id'), 'fixture_lineups', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_fixture_lineups_id'), 'fixture_lineups', ['id'], unique=False)
    op.create_index(op.f('ix_fixture_lineups_lineup_type_id'), 'fixture_lineups', ['lineup_type_id'], unique=False)
    op.create_index(op.f('ix_fixture_lineups_player_id'), 'fixture_lineups', ['player_id'], unique=False)
    op.create_index(op.f('ix_fixture_lineups_sportmonks_lineup_id'), 'fixture_lineups', ['sportmonks_lineup_id'], unique=True)
    op.create_index(op.f('ix_fixture_lineups_team_id'), 'fixture_lineups', ['team_id'], unique=False)
    op.create_table('fixture_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('sportmonks_weather_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('metric', sa.String(length=30), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_weather_fixture_id'), 'fixture_weather', ['fixture_id'], unique=True)
    op.create_index(op.f('ix_fixture_weather_id'), 'fixture_weather', ['id'], unique=False)
    op.create_index(op.f('ix_fixture_weather_sportmonks_weather_id'), 'fixture_weather', ['sportmonks_weather_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixture_weather_sportmonks_weather_id'), table_name='fixture_weather')
    op.drop_index(op.f('ix_fixture_weather_id'), table_name='fixture_weather')
    op.drop_index(op.f('ix_fixture_weather_fixture_id'), table_name='fixture_weather')
    op.drop_table('fixture_weather')
    op.drop_index(op.f('ix_fixture_lineups_team_id'), table_name='fixture_lineups')
    op.drop_index(op.f('ix_fixture_lineups_sportmonks_lineup_id'), table_name='fixture_lineups')
    op.drop_index(op.f('ix_fixture_lineups_player_id'), table_name='fixture_lineups')
    op.drop_index(op.f('ix_fixture_lineups_lineup_type_id'), table_name='fixture_lineups')
    op.drop_index(op.f('ix_fixture_lineups_id'), table_name='fixture_lineups')
    op.drop_index(op.f('ix_fixture_lineups_fixture_id'), table_name='fixture_lineups')
    op.drop_table('fixture_lineups')
    op.drop_index(op.f('ix_fixture_absences_team_id'), table_name='fixture_absences')
    op.drop_index(op.f('ix_fixture_absences_sportmonks_absence_id'), table_name='fixture_absences')
    op.drop_index(op.f('ix_fixture_absences_player_id'), table_name='fixture_absences')
    op.drop_index(op.f('ix_fixture_absences_id'), table_name='fixture_absences')
    op.drop_index(op.f('ix_fixture_absences_fixture_id'), table_name='fixture_absences')
    op.drop_index(op.f('ix_fixture_absences_absence_type_id'), table_name='fixture_absences')
    op.drop_table('fixture_absences')
    # ### end Alembic commands ###
