"""add match statistics table

Revision ID: 84d10db5983c
Revises: 3407cd56ad47
Create Date: 2026-07-14 08:52:31.435214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d10db5983c'
down_revision: Union[str, Sequence[str], None] = '3407cd56ad47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('possession', sa.Float(), nullable=True),
    sa.Column('corners', sa.Float(), nullable=True),
    sa.Column('goals', sa.Float(), nullable=True),
    sa.Column('yellow_cards', sa.Float(), nullable=True),
    sa.Column('red_cards', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_statistics_fixture_id'), 'match_statistics', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_match_statistics_id'), 'match_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_match_statistics_team_id'), 'match_statistics', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_statistics_team_id'), table_name='match_statistics')
    op.drop_index(op.f('ix_match_statistics_id'), table_name='match_statistics')
    op.drop_index(op.f('ix_match_statistics_fixture_id'), table_name='match_statistics')
    op.drop_table('match_statistics')
    # ### end Alembic commands ###
