"""add competition venue referee fields

Revision ID: 872c062b6914
Revises: a09ad16ce217
Create Date: 2026-07-24 13:15:58.499699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872c062b6914'
down_revision: Union[str, Sequence[str], None] = 'a09ad16ce217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('league_name', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('league_logo', sa.String(length=500), nullable=True))
    op.add_column('matches', sa.Column('season_name', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('round_name', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('stage_name', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('venue_name', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('venue_city', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('venue_capacity', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('venue_image', sa.String(length=500), nullable=True))
    op.add_column('matches', sa.Column('referee_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'referee_name')
    op.drop_column('matches', 'venue_image')
    op.drop_column('matches', 'venue_capacity')
    op.drop_column('matches', 'venue_city')
    op.drop_column('matches', 'venue_name')
    op.drop_column('matches', 'stage_name')
    op.drop_column('matches', 'round_name')
    op.drop_column('matches', 'season_name')
    op.drop_column('matches', 'league_logo')
    op.drop_column('matches', 'league_name')
    # ### end Alembic commands ###
