"""create elo history table

Revision ID: aa7caa10ff60
Revises: 84d10db5983c
Create Date: 2026-07-16 00:46:19.797067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7caa10ff60'
down_revision: Union[str, Sequence[str], None] = '84d10db5983c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_elo_before', sa.Integer(), nullable=False),
    sa.Column('away_elo_before', sa.Integer(), nullable=False),
    sa.Column('home_elo_change', sa.Integer(), nullable=False),
    sa.Column('away_elo_change', sa.Integer(), nullable=False),
    sa.Column('home_elo_after', sa.Integer(), nullable=False),
    sa.Column('away_elo_after', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elo_history_away_team_id'), 'elo_history', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_elo_history_home_team_id'), 'elo_history', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_elo_history_id'), 'elo_history', ['id'], unique=False)
    op.create_index(op.f('ix_elo_history_match_id'), 'elo_history', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elo_history_match_id'), table_name='elo_history')
    op.drop_index(op.f('ix_elo_history_id'), table_name='elo_history')
    op.drop_index(op.f('ix_elo_history_home_team_id'), table_name='elo_history')
    op.drop_index(op.f('ix_elo_history_away_team_id'), table_name='elo_history')
    op.drop_table('elo_history')
    # ### end Alembic commands ###
