"""add payments table
Revision ID: cd3cdc7326eb
Revises: fc75b89dd727
Create Date: 2026-08-08 17:07:54.010291
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
revision: str = "cd3cdc7326eb"
down_revision: Union[str, Sequence[str], None] = "fc75b89dd727"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    op.create_table(
        "payments",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "plan_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "provider_payment_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "provider_customer_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "provider_subscription_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "amount_minor",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "idempotency_key",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "failure_code",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "failure_message",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "paid_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["subscription_plans.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "provider_payment_id",
            name="uq_payments_provider_payment_id",
        ),
    )
    op.create_index(
        "ix_payments_id",
        "payments",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_payments_idempotency_key",
        "payments",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        "ix_payments_paid_at",
        "payments",
        ["paid_at"],
        unique=False,
    )
    op.create_index(
        "ix_payments_plan_id",
        "payments",
        ["plan_id"],
        unique=False,
    )
    op.create_index(
        "ix_payments_provider",
        "payments",
        ["provider"],
        unique=False,
    )
    op.create_index(
        "ix_payments_provider_customer_id",
        "payments",
        ["provider_customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_payments_provider_subscription_id",
        "payments",
        ["provider_subscription_id"],
        unique=False,
    )
    op.create_index(
        "ix_payments_status",
        "payments",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_payments_user_id",
        "payments",
        ["user_id"],
        unique=False,
    )
def downgrade() -> None:
    op.drop_index(
        "ix_payments_user_id",
        table_name="payments",
    )
    op.drop_index(
        "ix_payments_status",
        table_name="payments",
    )
    op.drop_index(
        "ix_payments_provider_subscription_id",
        table_name="payments",
    )
    op.drop_index(
        "ix_payments_provider_customer_id",
        table_name="payments",
    )
    op.drop_index(
        "ix_payments_provider",
        table_name="payments",
    )
    op.drop_index(
        "ix_payments_plan_id",
        table_name="payments",
    )
    op.drop_index(
        "ix_payments_paid_at",
        table_name="payments",
    )
    op.drop_index(
        "ix_payments_idempotency_key",
        table_name="payments",
    )
    op.drop_index(
        "ix_payments_id",
        table_name="payments",
    )
    op.drop_table("payments")
