from __future__ import annotations

from math import exp, factorial
from typing import Any


class MatchEventsEngineError(RuntimeError):
    """Raised when match-event prediction cannot be calculated."""


class MatchEventsEngine:
    """
    Predict expected corners and yellow cards.

    The engine is deterministic and uses normalized features already
    generated by FeatureEngineering and the fixture-context analyzers.
    """

    CORNER_LINES = (
        7.5,
        8.5,
        9.5,
        10.5,
        11.5,
    )

    YELLOW_CARD_LINES = (
        2.5,
        3.5,
        4.5,
        5.5,
    )

    MAX_POISSON_EVENTS = 40

    @classmethod
    def calculate(
        cls,
        features: dict[str, Any],
    ) -> dict[str, Any]:
        if not isinstance(features, dict):
            raise TypeError(
                "features must be a dictionary."
            )

        corners = cls._calculate_corners(features)
        yellow_cards = cls._calculate_yellow_cards(
            features
        )

        return {
            "corners": corners,
            "yellow_cards": yellow_cards,
            "data_quality": cls._data_quality(
                features
            ),
        }

    @classmethod
    def _calculate_corners(
        cls,
        features: dict[str, Any],
    ) -> dict[str, Any]:
        home_base = cls._clamp(
            cls._number(
                features.get("home_corners"),
                default=5.0,
            ),
            1.5,
            10.0,
        )

        away_base = cls._clamp(
            cls._number(
                features.get("away_corners"),
                default=5.0,
            ),
            1.5,
            10.0,
        )

        home_shots = cls._clamp(
            cls._number(
                features.get("home_shots"),
                default=12.0,
            ),
            3.0,
            30.0,
        )

        away_shots = cls._clamp(
            cls._number(
                features.get("away_shots"),
                default=12.0,
            ),
            3.0,
            30.0,
        )

        home_possession = cls._clamp(
            cls._number(
                features.get("home_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        away_possession = cls._clamp(
            cls._number(
                features.get("away_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        home_fatigue = cls._clamp(
            cls._number(
                features.get("home_fatigue_factor"),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        away_fatigue = cls._clamp(
            cls._number(
                features.get("away_fatigue_factor"),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        weather_severity = cls._clamp(
            cls._number(
                features.get("weather_severity"),
                default=0.0,
            ),
            0.0,
            0.10,
        )

        home_shot_factor = cls._clamp(
            1.0 + (
                (home_shots - 12.0) * 0.012
            ),
            0.88,
            1.15,
        )

        away_shot_factor = cls._clamp(
            1.0 + (
                (away_shots - 12.0) * 0.012
            ),
            0.88,
            1.15,
        )

        home_possession_factor = cls._clamp(
            1.0 + (
                (home_possession - 50.0) * 0.004
            ),
            0.90,
            1.10,
        )

        away_possession_factor = cls._clamp(
            1.0 + (
                (away_possession - 50.0) * 0.004
            ),
            0.90,
            1.10,
        )

        weather_factor = cls._clamp(
            1.0 - weather_severity * 0.35,
            0.96,
            1.0,
        )

        home_expected = (
            home_base
            * home_shot_factor
            * home_possession_factor
            * home_fatigue
            * weather_factor
            * 1.03
        )

        away_expected = (
            away_base
            * away_shot_factor
            * away_possession_factor
            * away_fatigue
            * weather_factor
            * 0.97
        )

        home_expected = cls._clamp(
            home_expected,
            1.5,
            10.5,
        )

        away_expected = cls._clamp(
            away_expected,
            1.5,
            10.5,
        )

        total_expected = (
            home_expected + away_expected
        )

        over_probabilities = {
            cls._line_key(line): round(
                cls._probability_over(
                    mean=total_expected,
                    line=line,
                ),
                4,
            )
            for line in cls.CORNER_LINES
        }

        return {
            "home_expected": round(
                home_expected,
                2,
            ),
            "away_expected": round(
                away_expected,
                2,
            ),
            "total_expected": round(
                total_expected,
                2,
            ),
            "over_probabilities": (
                over_probabilities
            ),
            "most_likely_range": (
                cls._expected_range(
                    total_expected,
                    minimum=4,
                    maximum=18,
                )
            ),
        }

    @classmethod
    def _calculate_yellow_cards(
        cls,
        features: dict[str, Any],
    ) -> dict[str, Any]:
        home_base = cls._clamp(
            cls._number(
                features.get(
                    "home_yellow_cards"
                ),
                default=2.0,
            ),
            0.5,
            6.0,
        )

        away_base = cls._clamp(
            cls._number(
                features.get(
                    "away_yellow_cards"
                ),
                default=2.0,
            ),
            0.5,
            6.0,
        )

        home_fatigue = cls._clamp(
            cls._number(
                features.get(
                    "home_fatigue_factor"
                ),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        away_fatigue = cls._clamp(
            cls._number(
                features.get(
                    "away_fatigue_factor"
                ),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        home_possession = cls._clamp(
            cls._number(
                features.get("home_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        away_possession = cls._clamp(
            cls._number(
                features.get("away_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        home_low_possession_factor = cls._clamp(
            1.0 + max(
                0.0,
                50.0 - home_possession,
            ) * 0.005,
            1.0,
            1.12,
        )

        away_low_possession_factor = cls._clamp(
            1.0 + max(
                0.0,
                50.0 - away_possession,
            ) * 0.005,
            1.0,
            1.12,
        )

        home_fatigue_card_factor = cls._clamp(
            1.0 + (
                1.0 - home_fatigue
            ) * 0.60,
            1.0,
            1.08,
        )

        away_fatigue_card_factor = cls._clamp(
            1.0 + (
                1.0 - away_fatigue
            ) * 0.60,
            1.0,
            1.08,
        )

        home_expected = (
            home_base
            * home_low_possession_factor
            * home_fatigue_card_factor
            * 0.98
        )

        away_expected = (
            away_base
            * away_low_possession_factor
            * away_fatigue_card_factor
            * 1.02
        )

        home_expected = cls._clamp(
            home_expected,
            0.5,
            6.5,
        )

        away_expected = cls._clamp(
            away_expected,
            0.5,
            6.5,
        )

        total_expected = (
            home_expected + away_expected
        )

        over_probabilities = {
            cls._line_key(line): round(
                cls._probability_over(
                    mean=total_expected,
                    line=line,
                ),
                4,
            )
            for line in cls.YELLOW_CARD_LINES
        }

        return {
            "home_expected": round(
                home_expected,
                2,
            ),
            "away_expected": round(
                away_expected,
                2,
            ),
            "total_expected": round(
                total_expected,
                2,
            ),
            "over_probabilities": (
                over_probabilities
            ),
            "most_likely_range": (
                cls._expected_range(
                    total_expected,
                    minimum=1,
                    maximum=10,
                )
            ),
            "referee_adjusted": False,
        }

    @classmethod
    def _probability_over(
        cls,
        *,
        mean: float,
        line: float,
    ) -> float:
        threshold = int(line + 0.5)

        probability_under_or_equal = sum(
            cls._poisson_probability(
                mean=mean,
                count=count,
            )
            for count in range(
                0,
                threshold,
            )
        )

        return cls._clamp(
            1.0 - probability_under_or_equal,
            0.0,
            1.0,
        )

    @staticmethod
    def _poisson_probability(
        *,
        mean: float,
        count: int,
    ) -> float:
        if mean <= 0.0 or count < 0:
            return 0.0

        return (
            exp(-mean)
            * mean ** count
            / factorial(count)
        )

    @classmethod
    def _expected_range(
        cls,
        mean: float,
        *,
        minimum: int,
        maximum: int,
    ) -> dict[str, int]:
        spread = max(
            1,
            round(mean ** 0.5),
        )

        lower = max(
            minimum,
            round(mean - spread),
        )

        upper = min(
            maximum,
            round(mean + spread),
        )

        return {
            "minimum": int(lower),
            "maximum": int(upper),
        }

    @staticmethod
    def _data_quality(
        features: dict[str, Any],
    ) -> dict[str, Any]:
        corner_values = (
            features.get("home_corners"),
            features.get("away_corners"),
        )

        yellow_values = (
            features.get("home_yellow_cards"),
            features.get("away_yellow_cards"),
        )

        corners_complete = all(
            value is not None
            for value in corner_values
        )

        yellow_cards_complete = all(
            value is not None
            for value in yellow_values
        )

        return {
            "corners_complete": (
                corners_complete
            ),
            "yellow_cards_complete": (
                yellow_cards_complete
            ),
            "uses_referee_profile": False,
        }

    @staticmethod
    def _line_key(
        line: float,
    ) -> str:
        return (
            f"over_{line:.1f}"
            .replace(".", "_")
        )

    @staticmethod
    def _number(
        value: Any,
        *,
        default: float,
    ) -> float:
        if value is None or isinstance(
            value,
            bool,
        ):
            return float(default)

        try:
            return float(value)
        except (TypeError, ValueError):
            return float(default)

    @staticmethod
    def _clamp(
        value: float,
        minimum: float,
        maximum: float,
    ) -> float:
        return max(
            minimum,
            min(maximum, value),
        )
