from __future__ import annotations

from math import exp, factorial
from typing import Any


class MatchEventsEngineError(RuntimeError):
    """Raised when match-event prediction cannot be calculated."""


class MatchEventsEngine:
    """
    Predict expected corners, yellow cards, shots, and shots on target.

    The engine is deterministic and uses normalized features already
    generated by FeatureEngineering and the fixture-context analyzers.
    """

    CORNER_LINES = (
        7.5,
        8.5,
        9.5,
        10.5,
        11.5,
    )

    YELLOW_CARD_LINES = (
        2.5,
        3.5,
        4.5,
        5.5,
    )

    SHOT_LINES = (
        19.5,
        21.5,
        23.5,
        25.5,
        27.5,
        29.5,
    )

    SHOTS_ON_TARGET_LINES = (
        6.5,
        7.5,
        8.5,
        9.5,
        10.5,
        11.5,
    )

    MAX_POISSON_EVENTS = 60

    @classmethod
    def calculate(
        cls,
        features: dict[str, Any],
    ) -> dict[str, Any]:
        if not isinstance(features, dict):
            raise TypeError(
                "features must be a dictionary."
            )

        corners = cls._calculate_corners(features)
        yellow_cards = cls._calculate_yellow_cards(
            features
        )
        shots = cls._calculate_shots(features)
        possession = cls._calculate_possession(features)

        return {
            "corners": corners,
            "yellow_cards": yellow_cards,
            "shots": shots["shots"],
            "shots_on_target": shots[
                "shots_on_target"
            ],
            "possession": possession,
            "data_quality": cls._data_quality(
                features
            ),
        }

    @classmethod
    def _calculate_corners(
        cls,
        features: dict[str, Any],
    ) -> dict[str, Any]:
        home_base = cls._clamp(
            cls._number(
                features.get("home_corners"),
                default=5.0,
            ),
            1.5,
            10.0,
        )

        away_base = cls._clamp(
            cls._number(
                features.get("away_corners"),
                default=5.0,
            ),
            1.5,
            10.0,
        )

        home_shots = cls._clamp(
            cls._number(
                features.get("home_shots"),
                default=12.0,
            ),
            3.0,
            30.0,
        )

        away_shots = cls._clamp(
            cls._number(
                features.get("away_shots"),
                default=12.0,
            ),
            3.0,
            30.0,
        )

        home_possession = cls._clamp(
            cls._number(
                features.get("home_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        away_possession = cls._clamp(
            cls._number(
                features.get("away_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        home_fatigue = cls._clamp(
            cls._number(
                features.get("home_fatigue_factor"),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        away_fatigue = cls._clamp(
            cls._number(
                features.get("away_fatigue_factor"),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        weather_severity = cls._clamp(
            cls._number(
                features.get("weather_severity"),
                default=0.0,
            ),
            0.0,
            0.10,
        )

        home_shot_factor = cls._clamp(
            1.0 + (
                (home_shots - 12.0) * 0.012
            ),
            0.88,
            1.15,
        )

        away_shot_factor = cls._clamp(
            1.0 + (
                (away_shots - 12.0) * 0.012
            ),
            0.88,
            1.15,
        )

        home_possession_factor = cls._clamp(
            1.0 + (
                (home_possession - 50.0) * 0.004
            ),
            0.90,
            1.10,
        )

        away_possession_factor = cls._clamp(
            1.0 + (
                (away_possession - 50.0) * 0.004
            ),
            0.90,
            1.10,
        )

        weather_factor = cls._clamp(
            1.0 - weather_severity * 0.35,
            0.96,
            1.0,
        )

        home_expected = (
            home_base
            * home_shot_factor
            * home_possession_factor
            * home_fatigue
            * weather_factor
            * 1.03
        )

        away_expected = (
            away_base
            * away_shot_factor
            * away_possession_factor
            * away_fatigue
            * weather_factor
            * 0.97
        )

        home_expected = cls._clamp(
            home_expected,
            1.5,
            10.5,
        )

        away_expected = cls._clamp(
            away_expected,
            1.5,
            10.5,
        )

        total_expected = (
            home_expected + away_expected
        )

        over_probabilities = {
            cls._line_key(line): round(
                cls._probability_over(
                    mean=total_expected,
                    line=line,
                ),
                4,
            )
            for line in cls.CORNER_LINES
        }

        return {
            "home_expected": round(
                home_expected,
                2,
            ),
            "away_expected": round(
                away_expected,
                2,
            ),
            "total_expected": round(
                total_expected,
                2,
            ),
            "over_probabilities": (
                over_probabilities
            ),
            "explanation": {
                "method": "multiplicative_factors",
                "distribution": "poisson",
                "home": {
                    "base_average": round(
                        home_base,
                        3,
                    ),
                    "shots": round(
                        home_shots,
                        3,
                    ),
                    "possession": round(
                        home_possession,
                        3,
                    ),
                    "fatigue_factor": round(
                        home_fatigue,
                        4,
                    ),
                    "factors": {
                        "shots": round(
                            home_shot_factor,
                            4,
                        ),
                        "possession": round(
                            home_possession_factor,
                            4,
                        ),
                        "fatigue": round(
                            home_fatigue,
                            4,
                        ),
                        "weather": round(
                            weather_factor,
                            4,
                        ),
                        "venue": 1.03,
                    },
                },
                "away": {
                    "base_average": round(
                        away_base,
                        3,
                    ),
                    "shots": round(
                        away_shots,
                        3,
                    ),
                    "possession": round(
                        away_possession,
                        3,
                    ),
                    "fatigue_factor": round(
                        away_fatigue,
                        4,
                    ),
                    "factors": {
                        "shots": round(
                            away_shot_factor,
                            4,
                        ),
                        "possession": round(
                            away_possession_factor,
                            4,
                        ),
                        "fatigue": round(
                            away_fatigue,
                            4,
                        ),
                        "weather": round(
                            weather_factor,
                            4,
                        ),
                        "venue": 0.97,
                    },
                },
                "weather_severity": round(
                    weather_severity,
                    4,
                ),
                "formula": (
                    "base_average * shots_factor * "
                    "possession_factor * fatigue_factor * "
                    "weather_factor * venue_factor"
                ),
            },
            "most_likely_range": (
                cls._expected_range(
                    total_expected,
                    minimum=4,
                    maximum=18,
                )
            ),
        }

    @classmethod
    def _calculate_shots(
        cls,
        features: dict[str, Any],
    ) -> dict[str, Any]:
        home_base_shots = cls._clamp(
            cls._number(
                features.get("home_shots"),
                default=12.0,
            ),
            3.0,
            30.0,
        )

        away_base_shots = cls._clamp(
            cls._number(
                features.get("away_shots"),
                default=12.0,
            ),
            3.0,
            30.0,
        )

        home_base_on_target = cls._clamp(
            cls._number(
                features.get(
                    "home_shots_on_target"
                ),
                default=4.0,
            ),
            0.5,
            15.0,
        )

        away_base_on_target = cls._clamp(
            cls._number(
                features.get(
                    "away_shots_on_target"
                ),
                default=4.0,
            ),
            0.5,
            15.0,
        )

        home_possession = cls._clamp(
            cls._number(
                features.get("home_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        away_possession = cls._clamp(
            cls._number(
                features.get("away_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        home_attack_rating = cls._clamp(
            cls._number(
                features.get(
                    "home_attack_rating"
                ),
                default=50.0,
            ),
            20.0,
            85.0,
        )

        away_attack_rating = cls._clamp(
            cls._number(
                features.get(
                    "away_attack_rating"
                ),
                default=50.0,
            ),
            20.0,
            85.0,
        )

        home_attack_xg = cls._clamp(
            cls._number(
                features.get("home_attack_xg"),
                default=1.5,
            ),
            0.3,
            4.0,
        )

        away_attack_xg = cls._clamp(
            cls._number(
                features.get("away_attack_xg"),
                default=1.5,
            ),
            0.3,
            4.0,
        )

        home_accuracy = cls._clamp(
            cls._number(
                features.get(
                    "home_shot_accuracy"
                ),
                default=33.0,
            ),
            10.0,
            65.0,
        )

        away_accuracy = cls._clamp(
            cls._number(
                features.get(
                    "away_shot_accuracy"
                ),
                default=33.0,
            ),
            10.0,
            65.0,
        )

        home_availability = cls._clamp(
            cls._number(
                features.get(
                    "home_availability_factor"
                ),
                default=1.0,
            ),
            0.85,
            1.02,
        )

        away_availability = cls._clamp(
            cls._number(
                features.get(
                    "away_availability_factor"
                ),
                default=1.0,
            ),
            0.85,
            1.02,
        )

        home_fatigue = cls._clamp(
            cls._number(
                features.get(
                    "home_fatigue_factor"
                ),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        away_fatigue = cls._clamp(
            cls._number(
                features.get(
                    "away_fatigue_factor"
                ),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        weather_factor = cls._clamp(
            cls._number(
                features.get(
                    "weather_attack_factor"
                ),
                default=1.0,
            ),
            0.90,
            1.03,
        )

        home_possession_factor = cls._clamp(
            1.0 + (
                home_possession - 50.0
            ) * 0.003,
            0.92,
            1.08,
        )

        away_possession_factor = cls._clamp(
            1.0 + (
                away_possession - 50.0
            ) * 0.003,
            0.92,
            1.08,
        )

        home_attack_factor = cls._clamp(
            1.0 + (
                home_attack_rating - 50.0
            ) * 0.0025,
            0.92,
            1.10,
        )

        away_attack_factor = cls._clamp(
            1.0 + (
                away_attack_rating - 50.0
            ) * 0.0025,
            0.92,
            1.10,
        )

        home_xg_factor = cls._clamp(
            1.0 + (
                home_attack_xg - 1.5
            ) * 0.045,
            0.94,
            1.10,
        )

        away_xg_factor = cls._clamp(
            1.0 + (
                away_attack_xg - 1.5
            ) * 0.045,
            0.94,
            1.10,
        )

        home_expected_shots = (
            home_base_shots
            * home_possession_factor
            * home_attack_factor
            * home_xg_factor
            * home_availability
            * home_fatigue
            * weather_factor
            * 1.02
        )

        away_expected_shots = (
            away_base_shots
            * away_possession_factor
            * away_attack_factor
            * away_xg_factor
            * away_availability
            * away_fatigue
            * weather_factor
            * 0.98
        )

        home_expected_shots = cls._clamp(
            home_expected_shots,
            3.0,
            32.0,
        )

        away_expected_shots = cls._clamp(
            away_expected_shots,
            3.0,
            32.0,
        )

        total_expected_shots = (
            home_expected_shots
            + away_expected_shots
        )

        home_accuracy_ratio = cls._clamp(
            home_accuracy / 100.0,
            0.12,
            0.60,
        )

        away_accuracy_ratio = cls._clamp(
            away_accuracy / 100.0,
            0.12,
            0.60,
        )

        home_history_target_rate = cls._clamp(
            home_base_on_target
            / max(home_base_shots, 1.0),
            0.12,
            0.60,
        )

        away_history_target_rate = cls._clamp(
            away_base_on_target
            / max(away_base_shots, 1.0),
            0.12,
            0.60,
        )

        home_target_rate = (
            home_accuracy_ratio * 0.55
            + home_history_target_rate * 0.45
        )

        away_target_rate = (
            away_accuracy_ratio * 0.55
            + away_history_target_rate * 0.45
        )

        home_expected_on_target = (
            home_expected_shots
            * home_target_rate
        )

        away_expected_on_target = (
            away_expected_shots
            * away_target_rate
        )

        home_expected_on_target = cls._clamp(
            home_expected_on_target,
            0.5,
            min(15.0, home_expected_shots),
        )

        away_expected_on_target = cls._clamp(
            away_expected_on_target,
            0.5,
            min(15.0, away_expected_shots),
        )

        total_expected_on_target = (
            home_expected_on_target
            + away_expected_on_target
        )

        shots_over_probabilities = {
            cls._line_key(line): round(
                cls._probability_over(
                    mean=total_expected_shots,
                    line=line,
                ),
                4,
            )
            for line in cls.SHOT_LINES
        }

        target_over_probabilities = {
            cls._line_key(line): round(
                cls._probability_over(
                    mean=total_expected_on_target,
                    line=line,
                ),
                4,
            )
            for line in cls.SHOTS_ON_TARGET_LINES
        }

        return {
            "shots": {
                "home_expected": round(
                    home_expected_shots,
                    2,
                ),
                "away_expected": round(
                    away_expected_shots,
                    2,
                ),
                "total_expected": round(
                    total_expected_shots,
                    2,
                ),
                "over_probabilities": (
                    shots_over_probabilities
                ),
                "most_likely_range": (
                    cls._expected_range(
                        total_expected_shots,
                        minimum=8,
                        maximum=50,
                    )
                ),
            },
            "shots_on_target": {
                "home_expected": round(
                    home_expected_on_target,
                    2,
                ),
                "away_expected": round(
                    away_expected_on_target,
                    2,
                ),
                "total_expected": round(
                    total_expected_on_target,
                    2,
                ),
                "over_probabilities": (
                    target_over_probabilities
                ),
                "most_likely_range": (
                    cls._expected_range(
                        total_expected_on_target,
                        minimum=2,
                        maximum=24,
                    )
                ),
            },
        }

    @classmethod
    def _calculate_possession(
        cls,
        features: dict[str, Any],
    ) -> dict[str, Any]:
        home_base = cls._clamp(
            cls._number(
                features.get("home_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )
        away_base = cls._clamp(
            cls._number(
                features.get("away_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        home_attack = cls._number(
            features.get("home_attack_rating"),
            default=50.0,
        )
        away_attack = cls._number(
            features.get("away_attack_rating"),
            default=50.0,
        )
        home_shots = cls._number(
            features.get("home_shots"),
            default=12.0,
        )
        away_shots = cls._number(
            features.get("away_shots"),
            default=12.0,
        )
        home_form = cls._number(
            features.get("home_form_points"),
            default=5.0,
        )
        away_form = cls._number(
            features.get("away_form_points"),
            default=5.0,
        )

        strength_difference = (
            (home_attack - away_attack) * 0.10
            + (home_shots - away_shots) * 0.35
            + (home_form - away_form) * 0.18
        )

        home_score = home_base + strength_difference
        away_score = away_base - strength_difference

        total_score = home_score + away_score

        if total_score <= 0:
            home_expected = 50.0
        else:
            home_expected = (
                home_score / total_score
            ) * 100.0

        home_expected = cls._clamp(
            home_expected,
            25.0,
            75.0,
        )
        away_expected = 100.0 - home_expected

        home_expected = round(home_expected, 2)
        away_expected = round(
            100.0 - home_expected,
            2,
        )

        difference = round(
            abs(home_expected - away_expected),
            2,
        )

        if difference < 3.0:
            dominant_team = "balanced"
            dominance_level = "balanced"
        elif home_expected > away_expected:
            dominant_team = "home"
            dominance_level = (
                cls._possession_dominance_level(
                    difference
                )
            )
        else:
            dominant_team = "away"
            dominance_level = (
                cls._possession_dominance_level(
                    difference
                )
            )

        return {
            "home_expected": home_expected,
            "away_expected": away_expected,
            "total": round(
                home_expected + away_expected,
                2,
            ),
            "difference": difference,
            "dominant_team": dominant_team,
            "dominance_level": dominance_level,
            "normalized": True,
        }

    @staticmethod
    def _possession_dominance_level(
        difference: float,
    ) -> str:
        if difference < 3.0:
            return "balanced"
        if difference < 8.0:
            return "slight"
        if difference < 15.0:
            return "moderate"
        return "strong"

    @classmethod
    def _calculate_yellow_cards(
        cls,
        features: dict[str, Any],
    ) -> dict[str, Any]:
        home_base = cls._clamp(
            cls._number(
                features.get(
                    "home_yellow_cards"
                ),
                default=2.0,
            ),
            0.5,
            6.0,
        )

        away_base = cls._clamp(
            cls._number(
                features.get(
                    "away_yellow_cards"
                ),
                default=2.0,
            ),
            0.5,
            6.0,
        )

        home_fatigue = cls._clamp(
            cls._number(
                features.get(
                    "home_fatigue_factor"
                ),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        away_fatigue = cls._clamp(
            cls._number(
                features.get(
                    "away_fatigue_factor"
                ),
                default=1.0,
            ),
            0.88,
            1.02,
        )

        home_possession = cls._clamp(
            cls._number(
                features.get("home_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        away_possession = cls._clamp(
            cls._number(
                features.get("away_possession"),
                default=50.0,
            ),
            25.0,
            75.0,
        )

        home_low_possession_factor = cls._clamp(
            1.0 + max(
                0.0,
                50.0 - home_possession,
            ) * 0.005,
            1.0,
            1.12,
        )

        away_low_possession_factor = cls._clamp(
            1.0 + max(
                0.0,
                50.0 - away_possession,
            ) * 0.005,
            1.0,
            1.12,
        )

        home_fatigue_card_factor = cls._clamp(
            1.0 + (
                1.0 - home_fatigue
            ) * 0.60,
            1.0,
            1.08,
        )

        away_fatigue_card_factor = cls._clamp(
            1.0 + (
                1.0 - away_fatigue
            ) * 0.60,
            1.0,
            1.08,
        )

        home_expected = (
            home_base
            * home_low_possession_factor
            * home_fatigue_card_factor
            * 0.98
        )

        away_expected = (
            away_base
            * away_low_possession_factor
            * away_fatigue_card_factor
            * 1.02
        )

        home_expected = cls._clamp(
            home_expected,
            0.5,
            6.5,
        )

        away_expected = cls._clamp(
            away_expected,
            0.5,
            6.5,
        )

        total_expected = (
            home_expected + away_expected
        )

        over_probabilities = {
            cls._line_key(line): round(
                cls._probability_over(
                    mean=total_expected,
                    line=line,
                ),
                4,
            )
            for line in cls.YELLOW_CARD_LINES
        }

        return {
            "home_expected": round(
                home_expected,
                2,
            ),
            "away_expected": round(
                away_expected,
                2,
            ),
            "total_expected": round(
                total_expected,
                2,
            ),
            "over_probabilities": (
                over_probabilities
            ),
            "explanation": {
                "method": "multiplicative_factors",
                "distribution": "poisson",
                "home": {
                    "base_average": round(
                        home_base,
                        3,
                    ),
                    "possession": round(
                        home_possession,
                        3,
                    ),
                    "fatigue_factor": round(
                        home_fatigue,
                        4,
                    ),
                    "factors": {
                        "low_possession": round(
                            home_low_possession_factor,
                            4,
                        ),
                        "fatigue": round(
                            home_fatigue_card_factor,
                            4,
                        ),
                        "venue": 0.98,
                    },
                },
                "away": {
                    "base_average": round(
                        away_base,
                        3,
                    ),
                    "possession": round(
                        away_possession,
                        3,
                    ),
                    "fatigue_factor": round(
                        away_fatigue,
                        4,
                    ),
                    "factors": {
                        "low_possession": round(
                            away_low_possession_factor,
                            4,
                        ),
                        "fatigue": round(
                            away_fatigue_card_factor,
                            4,
                        ),
                        "venue": 1.02,
                    },
                },
                "referee_adjusted": False,
                "formula": (
                    "base_average * low_possession_factor * "
                    "fatigue_card_factor * venue_factor"
                ),
            },
            "most_likely_range": (
                cls._expected_range(
                    total_expected,
                    minimum=1,
                    maximum=10,
                )
            ),
            "referee_adjusted": False,
        }

    @classmethod
    def _probability_over(
        cls,
        *,
        mean: float,
        line: float,
    ) -> float:
        threshold = int(line + 0.5)

        probability_under_or_equal = sum(
            cls._poisson_probability(
                mean=mean,
                count=count,
            )
            for count in range(
                0,
                threshold,
            )
        )

        return cls._clamp(
            1.0 - probability_under_or_equal,
            0.0,
            1.0,
        )

    @staticmethod
    def _poisson_probability(
        *,
        mean: float,
        count: int,
    ) -> float:
        if mean <= 0.0 or count < 0:
            return 0.0

        return (
            exp(-mean)
            * mean ** count
            / factorial(count)
        )

    @classmethod
    def _expected_range(
        cls,
        mean: float,
        *,
        minimum: int,
        maximum: int,
    ) -> dict[str, int]:
        spread = max(
            1,
            round(mean ** 0.5),
        )

        lower = max(
            minimum,
            round(mean - spread),
        )

        upper = min(
            maximum,
            round(mean + spread),
        )

        return {
            "minimum": int(lower),
            "maximum": int(upper),
        }

    @staticmethod
    def _data_quality(
        features: dict[str, Any],
    ) -> dict[str, Any]:
        corner_values = (
            features.get("home_corners"),
            features.get("away_corners"),
        )

        yellow_values = (
            features.get("home_yellow_cards"),
            features.get("away_yellow_cards"),
        )

        shot_values = (
            features.get("home_shots"),
            features.get("away_shots"),
        )

        shots_on_target_values = (
            features.get("home_shots_on_target"),
            features.get("away_shots_on_target"),
        )

        possession_values = (
            features.get("home_possession"),
            features.get("away_possession"),
        )

        corners_complete = all(
            value is not None
            for value in corner_values
        )

        yellow_cards_complete = all(
            value is not None
            for value in yellow_values
        )

        shots_complete = all(
            value is not None
            for value in shot_values
        )

        shots_on_target_complete = all(
            value is not None
            for value in shots_on_target_values
        )

        possession_complete = all(
            value is not None
            for value in possession_values
        )

        return {
            "corners_complete": (
                corners_complete
            ),
            "yellow_cards_complete": (
                yellow_cards_complete
            ),
            "shots_complete": shots_complete,
            "shots_on_target_complete": (
                shots_on_target_complete
            ),
            "possession_complete": (
                possession_complete
            ),
            "uses_referee_profile": False,
        }

    @staticmethod
    def _line_key(
        line: float,
    ) -> str:
        return (
            f"over_{line:.1f}"
            .replace(".", "_")
        )

    @staticmethod
    def _number(
        value: Any,
        *,
        default: float,
    ) -> float:
        if value is None or isinstance(
            value,
            bool,
        ):
            return float(default)

        try:
            return float(value)
        except (TypeError, ValueError):
            return float(default)

    @staticmethod
    def _clamp(
        value: float,
        minimum: float,
        maximum: float,
    ) -> float:
        return max(
            minimum,
            min(maximum, value),
        )
